BoxHeight: ''
BoxWidth: ''
DLCfolderPath: ''
DLCvideoPaths: []
Name: ''
Path: ''
data:
  ' Videos': []
  Feature 1: []
  Feature 2: []
folderPath: ''
numFeatures: '2'
uncertainty: 0.6
videoPaths: []
zone: []
